# PingPongOS - PingPong Operating System
# © Prof. Carlos A. Maziero, DINF UFPR
# Versão 2.1 -- 06/2026

# ATENÇÃO: ESTE ARQUIVO NÃO DEVE SER ALTERADO;
# ALTERAÇÕES SERÃO DESCARTADAS NA CORREÇÃO.

# flags adicionais
CPPFLAGS += -I../ -I../kernel/ -I../lib/

# compila arquivo de teste
ping%:
	$(CC) $(CFLAGS) $(CPPFLAGS) -c -o $@.o $@.c
